### PR TITLE
Fix tests, add in git url fields and update the pkgfile download uri

### PR DESCRIPTION
**Pull request by jnbek**

### CODE REVIEW

**Comment by juster** [comment]
Looks good! I'll work on a release. By the way, would you be interested in maintaining this module and/or CPANPLUS::Dist::Arch?

**Comment by jnbek** [comment]
Ehh... maybe :) I've noticed you've hinted around to this.. I suppose I've always seen this day coming :-P I would still like to have you in an advisory role, if that's ok.

**Comment by juster** [comment]
Yeah we could keep in touch. You could always shoot me an email if you have a question and I can help study the code or bug. I am just out of touch with ArchLinux so it would be kind of better to have someone who is more emotionally involved with Arch. Motivation is key and you also seem very enthusiastic about perl in general. It seems natural to me that you would be a replacement maintainer.

I'm not sure if you have experienced this, but CPAN modules releases are very similar to submitting user packages on the AUR. You build and test things in a separate directory. Then you create the distfile/tarball and upload it through your PAUSE account on the CPAN. I would have to transfer ownership of the modules, on CPAN, to your author ID of course. But it's basically identical to what you are already doing.

**Comment by jnbek** [comment]
OK, cool, I've had a PAUSE account for years, but I've never actually used
it, lol... Is there anything you need to do at the CPAN end to pass
ownership? I'd prefer to avoid that horrid "UNAUTHORIZED" warning I see
from time to time on modules.

On Fri, Sep 25, 2015 at 3:07 PM, Justin Davis <notifications@github.com>
wrote:

> Yeah we could keep in touch. You could always shoot me an email if you
> have a question and I can help study the code or bug. I am just out of
> touch with ArchLinux so it would be kind of better to have someone who is
> more emotionally involved with Arch. Motivation is key and you also seem
> very enthusiastic about perl in general. It seems natural to me that you
> would be a replacement maintainer.
>
> I'm not sure if you have experienced this, but CPAN modules releases are
> very similar to submitting user packages on the AUR. You build and test
> things in a separate directory. Then you create the distfile/tarball and
> upload it through your PAUSE account on the CPAN. I would have to transfer
> ownership of the modules, on CPAN, to your author ID of course. But it's
> basically identical to what you are already doing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juster/perl-www-aur/pull/2#issuecomment-143355031>.
>



-- 
Thanks,
John D Jones III
Perl Zealot/BOFH
http://www.zoelife4u.org/
jnbek1972@gmail.com
unixgeek1972@gmail.com
Where Earth and Spirit Unite

**Comment by juster** [comment]
I just transfered the WWW::AUR namespace of modules to you (JNBEK) on CPAN. You are now the maintainer and I am the co-maintainer according to CPAN. I will do the CPAN+::Dist::Arch next if you are interested.

**Comment by jnbek** [comment]
I am interested

**Comment by juster** [comment]
Alrighty I transferred CPANPLUS::Dist::Arch to you. Weehee!

**Pull request merged**
